language: python
sudo: false

addons:
  apt:
    packages:
      - libzzip-dev

env:
  - LUA="lua 5.1"
  - LUA="lua 5.2"
  - LUA="lua 5.3"
  - LUA="luajit 2.0"
  - LUA="luajit 2.1"

before_install:
  - pip install hererocks
  - hererocks env --$LUA --luarocks latest
  - source env/bin/activate

install:
  - luarocks make CFLAGS="-O0 -fPIC --coverage" LIBFLAG="-shared --coverage"

before_script:
  - luarocks install busted

script:
  - busted

after_success:
  - gcov -o src src/luazip.c
  - bash <(curl -s https://codecov.io/bash) -X gcov -X coveragepy
